version: '3.3'
services:
  jakartaee-hello-world:
    build: .
    container_name: jakartaee-hello-world
    image: 'jakartaee-hello-world:v1'    
    ports:
    - '8080:8080'
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    depends_on:
      fluentd:
        condition: service_started
    networks:
      - elastic-network

  fluentd:
    build: ./fluentd
    container_name: fluentd
    user: root
    volumes:
    - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs    
    - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elastic-network

  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
    - node.name=elasticsearch
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"    
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - elastic-network

  kibana:
    image: kibana:7.17.13
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_started
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge